env:
  RUBY_VERSION: 2.6

name: spec
on: [push, pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install gem dependencies
        run: |
          gem install bundler
          bundler install
      - name: Run tests
        run: bundler exec rspec
      - name: Upload coverage results    
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: my-artifact
          path: |
            ${{ github.workspace }}/coverage
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2